CREATE TABLE IF NOT EXISTS CARTEIRA (
    ID SERIAL PRIMARY KEY, NOME_COMPLETO VARCHAR(100), CPF BIGINT, EMAIL VARCHAR(100), SENHA VARCHAR(100), TIPO INT, SALDO DECIMAL(10, 2), "VERSION" BIGINT
);

CREATE UNIQUE INDEX IF NOT EXISTS cpf_idx ON CARTEIRA (CPF);

CREATE UNIQUE INDEX IF NOT EXISTS email_idx ON CARTEIRA (EMAIL);

CREATE TABLE IF NOT EXISTS TRANSACAO (
    ID SERIAL PRIMARY KEY, PAGADOR INT, RECEBEDOR INT, VALOR DECIMAL(10, 2), DATA_CRIACAO TIMESTAMP, FOREIGN KEY (PAGADOR) REFERENCES CARTEIRA (ID), FOREIGN KEY (RECEBEDOR) REFERENCES CARTEIRA (ID)
);